export { App } from './app/App'
export { useAppStore } from './stores'
export { useCurrentProject, useProjectAgents, useResolvedConfig, useServices } from './hooks'
export { getServices, configureServices, ServiceProvider, createMockServices } from './services'
export type { ServiceContainer } from './services'
export * from './components'
export * from './lib/motion'
