export type {
  IProjectService,
  IAgentService,
  IConversationService,
  ITaskService,
  IWorkspaceService,
  ISkillService,
  IMCPService,
  ISettingsService,
  ICronJobService,
  IDashboardService,
  IGlobalDashboardService,
  IPermissionsConfigService,
  ISpeechService,
} from '@golemancy/shared'
